server:
  port: 8093

spring:
  # 多数据源配置
  datasource:
    # MySQL配置
    mysql:
      username:
      password:
      url: jdbc:mysql://localhost:3306/spring-ai-chat?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: Retail_HikariCP
        minimum-idle: 15 # 最小空闲连接数量
        idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
        maximum-pool-size: 25 # 连接池最大连接数，默认是10
        auto-commit: true  # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1
    # PgVector配置
    pgvector:
      driver-class-name: org.postgresql.Driver
      username:
      password:
      url: jdbc:postgresql:///postgres
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
  ai:
    # OpenAI配置
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key:
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1536
    # Ollama配置
    ollama:
      base-url:
      chat:
        model: deepseek-r1:1.5b
    # MCP配置
    mcp:
      client:
        sse:
          connections:
            server:
              url: http://localhost:18093

# MyBatis配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

# Http客户端配置
okhttpclient:
  config:
    connectTimeOut: 600
    writeTimeOut: 600
    readTimeOut: 600

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
